### ISSUE TITLE
Not returning userlist

### ISSUE THREAD

**Issue by blynn-dev** [BlackMac/ostkit.js#1]
I looked at the API here https://dev.ost.com/docs/api_users_list.html

for some reason I'm gettin undefined for result2.

```
app.get('/userList', (req, res) => {
    ost.usersList().then((data) => {
        var result2 = "User List "+data.economy_users.name;
        res.send(result2);
    });
})
```

**Comment by blynn-dev** [comment]
I think I figured it out, as long as I just pass data I get the json feed. This is awesome thanks!

**Comment by BlackMac** [comment]
Great. data.economy_users is an array by the way.
