### ISSUE TITLE
transaction_hash?

### ISSUE THREAD

**Issue by blynn-dev** [BlackMac/ostkit.js#2]
Is there a reason why "transaction_hash": null ? I'm confused how do I pass that value or do I not need it and my transaction is going though?

```
{
"transaction_uuid": "d4e3b769-4c58-4a49-a1b1-fe6d06563b29",
"transaction_hash": null,
"from_uuid": "a5c3b6e5-d030-4cd0-b7fa-e6186c81b00b",
"to_uuid": "c6ff7381-99ef-4562-bc66-6ac0b1c905e1",
"transaction_kind": "ECO Transaction"
}
```

**Comment by realJayNay** [comment]
This means the transaction has not been fully processed yet on the OpenST side chains. Try again later.

**Comment by blynn-dev** [comment]
in this repos's docs it says.. using this method "`transactiontypesExecute`" you need to define three objects `({from_uuid, to_uuid, transaction_kind})`  when in the ost docs, you need `/transaction-types/execute?api_key=API_KEY&from_uuid=FROM_UUID&request_timestamp=EPOCH_TIME_SEC&to_uuid=TO_UUID&transaction_kind=NAME`  

do I need to pass `request_timestamp` how is that defined?

**Comment by BlackMac** [comment]
No, `request_timestamp` is autogenerated and `api_key` is added automatically (you pass it when you create an instance of Ostkit)

**Comment by blynn-dev** [comment]
@BlackMac Is there a place to look specifically if I sent a transaction went though ?  would I check the kit.ost.com logs or try pulling back the `ost.transactiontypesStatus` or `ost.transactiontypesList`

**Comment by BlackMac** [comment]
When you execute `transactiontypesExecute`you will get back the transaction ID. You can then register a callback for status changes:

```js
var ok = new Ostkit("YOUR_API_KEY", "YOUR_API_SECRET");
// replace FROM and TO with user UUIDs
ok.transactiontypesExecute({from_uuid:"FROM",to_uuid:"TO", transaction_kind:"TRANSACTION KIND NAME"}).then(transaction_result => {
  ok.monitorTransaction(transaction_result.transaction_uuid , function(transaction) {
    if (transaction.status == "complete") {
        console.log("Successful transaction")
    } else if (transaction.status == "failed") {
        console.log("Transaction failed")
    } else {
        console.log("Status: ",transaction.status)
    }
  })
});
```
